import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./Components/Shared/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>
       <div> <Sidebar/></div>
        {children}
        </body>
    </html>
  );
}
